source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '13.0'

target 'HLUIKit_Example' do
  pod 'HLinUIKit', :path => '../'
  pod 'HLinUIKit/Moya', :path => '../'
  pod 'HLinUIKit/Bluetooth', :path => '../'
  pod 'HLinUIKit/Realm', :path => '../'
  pod 'RxBluetoothKit', :git => 'https://github.com/U131025/RxBluetoothKit.git'
  
#  pod 'SmartCodable'
  pod 'ObjectMapper'

  target 'HLUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "XM53GK5D84"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
