source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '12.0'

target 'HLUIKit_Example' do
  pod 'HLinUIKit', :path => '../'
  pod 'HLinUIKit/Moya', :path => '../'
  pod 'HLinUIKit/Bluetooth', :path => '../'
  pod 'HLinUIKit/Realm', :path => '../'
  pod 'RxBluetoothKit', :git => 'https://github.com/U131025/RxBluetoothKit.git'
  
#  pod 'SmartCodable'
  pod 'ObjectMapper'

  target 'HLUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
